KG-12: add auth
lagunnna/sex-game pull request #3
Opened 2021-12-06 19:56 UTC by lagunnna

Task description: [youtrack](https://astashev.youtrack.cloud/issue/KG-12).

2021-12-06 20:55 UTC, programm1st requested changes

2021-12-06 20:55 UTC, programm1st commented on src/components/Dropdown.vue
> +    <button class="btn-toggle btn" @click.prevent="isOpen = !isOpen">
вынести в компьютед

2021-12-06 20:55 UTC, programm1st commented on src/layouts/AuthLayout.vue
> +    <Logo />
дропнуть этот лейаут, кнпоку просто скрывать по урлу

2021-12-06 20:55 UTC, programm1st commented on src/store/info.js
> +    info: (s) => s.info,
шо це за "S" лучше написать state полностью

2021-12-06 20:55 UTC, programm1st commented on src/store/info.js
> +      const { uid } = getAuth().currentUser;
лучше переменный называть полными словами, что бы при чтении с разу было понятно за что отвечает

2021-12-06 20:55 UTC, programm1st commented on src/views/Profile.vue
> +    this.name = this.info.name;
переделать, на компьютед с сеттером и гетером, скрин скинул в телегу

2021-12-07 09:32 UTC, lagunnna commented on src/store/info.js
> +    info: (s) => s.info,
>  Понял, принял

```suggestion
    info: (state) => state.info,
```

2021-12-07 09:54 UTC, lagunnna commented on src/components/Dropdown.vue
> +    <button class="btn-toggle btn" @click.prevent="isOpen = !isOpen">
Вынесла событие в функцию `toggleMenu()`:

![image](https://user-images.githubusercontent.com/65291920/145006474-858f6a71-bce1-4940-8242-26ee3d048850.png)

2021-12-07 11:32 UTC, lagunnna commented on src/store/info.js
> +      const { uid } = getAuth().currentUser;
Переименовала 

![image](https://user-images.githubusercontent.com/65291920/145021805-fc0b824e-4f08-4682-bfd2-dc37d62c5456.png)

2021-12-07 12:53 UTC, lagunnna commented on src/views/Profile.vue
> +    this.name = this.info.name;
Заменила на computed:

![image](https://user-images.githubusercontent.com/65291920/145032434-ff166777-e893-4897-9850-12584e158e77.png)

Добавила мутации в store:

![image](https://user-images.githubusercontent.com/65291920/145032418-581969cd-a627-49b8-9fcc-49dbee2d2239.png)

2021-12-07 19:09 UTC, programm1st requested changes

2021-12-07 19:09 UTC, programm1st commented on src/router/index.js
>      path: '/selectLevel',
для лучшей читаемости данного файла константу routes можно вынести в отдельный файлик и подключить сюда

файли с константой можно назвать routers.js и подключить сюда. тогда читаться все будет быстрее. Мы обычно их выносим в отдельный файлик

2021-12-07 19:09 UTC, programm1st commented on src/router/index.js
> +    next('/login');
надо убрать обязательную авторизацию для игры) Рега была для тренировки, нет никого резона делать регу обязательной

2021-12-07 19:09 UTC, programm1st commented on src/store/auth.js
> +          console.log(userCredential.user);
а надо ли в консоль выводить права пользователя?

2021-12-07 19:09 UTC, programm1st commented on src/views/Cards.vue
> +      >Следующая карточка</button>
Если честно, тяжело читать такой код, кажется в этом файлике не применялся линтер

2021-12-07 19:09 UTC, programm1st commented on src/views/Login.vue
> +        введите корректный email</b-form-invalid-feedback>
каша, когда у тебя тег начинается одной строке
а содержимое тега и закрытие на второй. Чуть ниже гораздо красивее и удобнее для чтения у тебя написано

2021-12-07 19:09 UTC, programm1st commented on src/views/Login.vue
> +      </b-form-invalid-feedback>
вот тут круто

тег открылся
  текст
тег закрылся

2021-12-07 19:09 UTC, programm1st commented on src/views/Login.vue
> +      </b-form-invalid-feedback>
гораздо проще читать такое

2021-12-07 19:09 UTC, programm1st commented on src/views/Profile.vue
> +      set(newValue) {
тут лучше не newValue а newName

2021-12-07 19:09 UTC, programm1st commented on src/views/Profile.vue
> +      set(newValue) {
по аналогии как выше

2021-12-07 19:09 UTC, programm1st commented on src/views/Profile.vue
> +    ...mapGetters(['info']),
раз уж ты использушь тут mapGetters, то давай тут сделаем еще и mapActions

2021-12-07 19:09 UTC, programm1st commented on src/store/info.js
> +    info: (state) => state.info,
по названию функции должно быть понятно что происходит внутри. 
Если это геттер, то надо писать getInfo
если метод тебе возвращает тип булеан то что-то типа isNewUser, обратить надо внимание именно на начало, на is. Так сразу становится понятно что будет возвращено и тоге и будет ли что-то возвращено

2021-12-08 11:02 UTC, lagunnna commented on src/router/index.js
> +    next('/login');
Уже убрала в предыдущем коммите(bc10a37), оставила защиту только для входа в профиль

2021-12-08 11:12 UTC, lagunnna commented on src/router/index.js
>      path: '/selectLevel',
Вынесла константу в отдельный файл routes.js (f695cb0).

2021-12-08 11:25 UTC, lagunnna commented on src/store/auth.js
> +        })
```suggestion

```

2021-12-08 11:30 UTC, lagunnna commented on src/store/auth.js
> +          console.log(userCredential.user);
Упс
Удалено (acfafeb).

2021-12-08 12:04 UTC, lagunnna commented on src/views/Profile.vue
> +      set(newValue) {
Заменила (f757093).

2021-12-08 12:05 UTC, lagunnna commented on src/views/Profile.vue
> +      set(newValue) {
Заменила название аргумента на isMan (f757093).

2021-12-08 12:06 UTC, lagunnna commented on src/views/Profile.vue
> +    ...mapGetters(['info']),
Добавила также mapMutations (f757093).

2021-12-08 14:17 UTC, lagunnna commented on src/views/Cards.vue
> +      >Следующая карточка</button>
Исправлено (bd812c9).

2021-12-08 14:17 UTC, lagunnna commented on src/views/Login.vue
> +        введите корректный email</b-form-invalid-feedback>
Исправлено (bd812c9).

2021-12-08 17:17 UTC, lagunnna commented on src/store/info.js
> +    info: (state) => state.info,
Изменила имена геттеров как в info.js, так и в level.js (3cc8ddd).

2021-12-10 20:51 UTC, lagunnna commented
Изменила структуру store: добавлены модули и константы (ef140c5).

2021-12-18 20:55 UTC, lagunnna commented
Добавлены базовые уведомления об ошибках пользователю (d24158b).

2021-12-20 13:24 UTC, merged